CREATE DATABASE GAMEVUI
GO
USE GAMEVUI
--CREATE TABLE 
CREATE TABLE TBL_QUESTION
(
	ID INT IDENTITY (1, 1) NOT NULL,
	QUESTION NVARCHAR(100),
	ANSWER_1 NVARCHAR(50),
	ANSWER_2 NVARCHAR(50),
	ANSWER_3 NVARCHAR(50),
	ANSWER_4 NVARCHAR(50),
	ANSWER_TIME INT,
	POINT INT,
	CONSTRAINT PK_TBL_QUESTION PRIMARY KEY(ID)
)
CREATE TABLE TBL_PLAYER
(
	PLAYER_ID INT IDENTITY(1, 1) NOT NULL,
	PLAYER_NAME NVARCHAR(50),
	CONSTRAINT PK_TBL_PLAYER PRIMARY KEY(PLAYER_ID)
)
CREATE TABLE TBL_RECORD
(
	RECORD_ID INT IDENTITY(1, 1) NOT NULL,
	PLAYER_ID INT,
	TOTAL_POINT INT,
	CONSTRAINT PK_TBL_RECORD PRIMARY KEY(RECORD_ID),
	CONSTRAINT FK_TBL_RECORD_TBL_PLAYER FOREIGN KEY (PLAYER_ID) REFERENCES TBL_PLAYER (PLAYER_ID)
)